name: OIDC Test

on:
  workflow_dispatch:   # 手動実行だけ

permissions:
  id-token: write      # OIDCに必須
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585008043652:role/github-actions-deploy-role
          aws-region: ap-northeast-1

      - name: Who am I
        run: aws sts get-caller-identity