name: Terraform Pipeline (Plan on push, Apply manual)

# このワークフローは通常のPlan/Apply用です

concurrency:
  group: terraform-dev              # 同時実行を禁止（state壊れ防止）
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
    paths:    [ 'terraform/**' ]
  pull_request:
    branches: [ main ]
    paths:    [ 'terraform/**' ]
  workflow_dispatch:
    inputs:
      do_apply:
        description: 'Run terraform apply (手動時のみ適用)'
        required: false
        type: boolean
        default: false   # 既定は Plan のみ

permissions:
  id-token: write                                # OIDCに必須
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/env/dev

    steps:
      # リポジトリのコードをチェックアウト
      - uses: actions/checkout@v4

      # OIDCでAWS認証を設定
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585008043652:role/github-actions-deploy-role
          aws-region: ap-northeast-1

      # Terraformのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # 既存のtfstateアーティファクトをダウンロード（reset_stateがtrueでない場合のみ）
      - name: Download tfstate artifact (dev)
        uses: actions/download-artifact@v4
        with:
          name: terraform-state-dev       # ← 任意だが固定名にする
          path: terraform/env/dev         # ← working-directory と同じ
        continue-on-error: true           # 初回は存在しないのでOK

      # Terraformの初期化
      - name: Terraform Init
        run: terraform init -input=false

      # 余計なtfvarsファイルを削除
      - name: Clean previous tfvars
        run: rm -f *.tfvars *.auto.tfvars || true

      # secretsからbase64エンコードされたdev.auto.tfvarsを作成
      - name: Write tfvars from secret (dev, base64)
        run: |
          rm -f dev.auto.tfvars || true
          printf "%s" "${{ secrets.TFVARS_DEV_B64 }}" | base64 -d > dev.auto.tfvars

      # Terraform Planを実行（自動実行はここまで）
      - name: Terraform Plan
        env:
          TF_IN_AUTOMATION: "true"   # CIでの実行を明示
          TF_INPUT: "false"          # 念のため環境変数でも無効化
        run: terraform plan -input=false -no-color -out=tfplan -var-file=./dev.auto.tfvars

      # Plan結果をアーティファクトとして保存
      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      # Applyはworkflow_dispatchで手動実行したときのみ実行
      - name: Terraform Apply (manual only)
        if: ${{ inputs.do_apply == true }}
        run: terraform apply -auto-approve tfplan

      # tfstateをアーティファクトとして保存（存在しない場合は警告のみ）
      - name: Upload tfstate artifact (dev)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state-dev
          path: |
            terraform/env/dev/terraform.tfstate
            terraform/env/dev/terraform.tfstate.backup
          retention-days: 90       # デフォルト90。必要に応じて調整
          if-no-files-found: warn  # 無ければ警告のみ
