

name: Terraform Destroy (dev)

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type I UNDERSTAND to confirm destructive action"
        required: true
        type: string
      reason:
        description: "Optional: reason/issue link for audit trail"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-destroy-dev
  cancel-in-progress: false

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/env/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585008043652:role/github-actions-deploy-role
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Download tfstate artifact (dev)
        uses: actions/download-artifact@v4
        with:
          name: terraform-state-dev
          path: terraform/env/dev
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -input=false

      - name: Clean previous tfvars
        run: rm -f *.tfvars *.auto.tfvars || true

      - name: Write tfvars from secret (dev, base64)
        run: |
          rm -f dev.auto.tfvars || true
          printf "%s" "${{ secrets.TFVARS_DEV_B64 }}" | base64 -d > dev.auto.tfvars

      - name: Confirm destroy input
        run: |
          if [ "${{ inputs.confirm_destroy }}" != "I UNDERSTAND" ]; then
            echo "::error::Destroy action not confirmed. Please type exactly 'I UNDERSTAND' in the confirm_destroy input."
            exit 1
          fi
          echo "Confirmed by user. Reason: '${{ inputs.reason }}'"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file=./dev.auto.tfvars

      - name: Upload tfstate artifact (dev)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state-dev
          path: |
            terraform/env/dev/terraform.tfstate
            terraform/env/dev/terraform.tfstate.backup
          retention-days: 90
          if-no-files-found: warn