name: Terraform Pipeline

on:
  push:
    branches: [ main ]      # mainブランチにpushで実行
    paths: [ 'infra/terraform/**' ]  # Terraform関連の変更時だけ
  workflow_dispatch:        # 手動実行も可能

permissions:
  id-token: write           # OIDCで必要
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/env/dev  # Terraformコードの場所

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::585008043652:role/github-actions-deploy-role
          aws-region: ap-northeast-1

      - name: Who am I
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply (manual only)
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan